In [1]:
pip install numpy

In [2]:
import numpy as np

# convertion of list into array

In [4]:
l=[]
for i in range (1,6):
    a=int(input("enter your no"))
    l.append(a)
print(l)


enter your no 1
enter your no 2
enter your no 3
enter your no 4
enter your no 4


[1, 2, 3, 4, 4]


In [8]:
a=np.array(l)
print(l)
print(type(l))

[1, 2, 3, 4, 4]
<class 'list'>


In [11]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr.shape
# x asiz or y axis

(2, 3)

In [13]:
arr.size
#total no of element

6

In [14]:
# to find the total no of observations and coloumns
# 0= axis , 1= y axis
arr.shape[0]
arr.shape[1]

3

In [ ]:
arr = np.array([1,2,3])
#to

In [17]:
arr = np.array([1+2j, 3-4j] , dtype=np.complex64)
arr.dtype

dtype('complex64')

In [18]:
arr = np.array([1+2j, 3-4j] , dtype='c8')
               
arr.dtype

dtype('complex64')

In [19]:
arr = np.array([1+2j, 3-4j] , dtype='complex64')
arr.dtype

dtype('complex64')

In [22]:
# to creat the identity matrix
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# to creat the identity matrix

arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
arr = np.eye(3,5 , k=2)


In [27]:
arr

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
arr = np.eye(3 , -2)
arr

ValueError: negative dimensions are not allowed

In [8]:
# convertion two dimention to one dimention
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[arr>5])
print[arr(arr>5) & (arr<8)]


[6 7 8 9]


TypeError: 'numpy.ndarray' object is not callable

In [9]:
c= arr[(arr>2) & (arr<11)]
print(c)

[3 4 5 6 7 8 9]


In [ ]:
#day 3

In [1]:
a=[1,2,3,4]
a[0]

1

In [2]:
a=[[1,2,3,4],[5,6,7,8]]
a[0][1]

2

In [4]:
a[0]=10
a

[10, [5, 6, 7, 8]]

In [6]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
b=a[0:1]
b

array([[1, 2, 3, 4]])

In [9]:
type(b)

numpy.ndarray

In [10]:
a = [1,2,3,4],[5,6,7,8]
a[0:3]

([1, 2, 3, 4], [5, 6, 7, 8])

In [11]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
a=np.array([1,2,3,4,5,6,7,8])
a[-1]
a[-1:-5]
# empty bcos step is on +v +ve side 

array([], dtype=int32)

In [15]:
arr = np.empty(5)
arr

array([2.12199579e-314, 1.26470949e-311, 6.81810591e-321, 1.26470949e-311,
       3.56169948e-317])

In [7]:
import numpy as np
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [8]:
arr = np.reshape(2,3)
arr

ValueError: cannot reshape array of size 1 into shape (3,)

In [11]:
# to convertion the shape of an array
arr2 = np.array([[1,2,3],[5,6,7]])
arr2

array([[1, 2, 3],
       [5, 6, 7]])

In [13]:
arr2 = np.reshape(3,2)
arr

ValueError: cannot reshape array of size 1 into shape (2,)

In [15]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [16]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [17]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr3 = np.add(arr1,arr2)
arr3

array([ 6,  8, 10, 12])

In [21]:
arr4= arr1 + arr2 
arr4


NameError: name 'arr5' is not defined

In [23]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8]) 

arr3 = np.concatenate((arr1,arr2),dtype="float32")
arr

array([1., 1., 1., 1., 1.])

In [24]:
pi install pandas

SyntaxError: invalid syntax (2565059655.py, line 1)

In [25]:
impord pandas as pd

SyntaxError: invalid syntax (2799684367.py, line 1)

In [26]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [1]:
import pandas as pd

In [4]:
pd.read_csv("C:/Users/raghu/Downloads/csv_file/customers-100.csv")

Index      Customer Id First Name Last Name  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter   
1       2  1Ef7b82A4CAAD10    Preston    Lozano   
2       3  6F94879bDAfE5a6        Roy     Berry   
3       4  5Cef8BFA16c5e3c      Linda     Olsen   
4       5  053d585Ab6b3159     Joanna    Bender   
..    ...              ...        ...       ...   
95     96  cb8E23e48d22Eae       Karl     Greer   
96     97  CeD220bdAaCfaDf       Lynn  Atkinson   
97     98  28CDbC0dFe4b1Db       Fred    Guerra   
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer   
99    100  2354a0E336A91A1   Clarence    Haynes   

                            Company               City  \
0                   Rasmussen Group       East Leonard   
1                       Vega-Gentry  East Jimmychester   
2                     Murillo-Perry      Isabelborough   
3   Dominguez, Mcmillan and Donovan         Bensonview   
4          Martin, Lang and Andrade     West Priscilla   
..                              ...                ...   
95                        Carey LLC       East Richard   
96            Ware, Burns and Oneal       New Bradview   
97                    Schmitt-Jones         Ortegaland   
98               Fitzgerald-Harrell    Lake Elijahview   
99               Le, Nash and Cross          Judymouth   

                       Country                 Phone 1  \
0                        Chile            229.077.5154   
1                     Djibouti              5153435776   
2          Antigua and Barbuda         +1-539-402-0259   
3           Dominican Republic  001-808-617-6467x12895   
4   Slovakia (Slovak Republic)  001-234-203-0635x76146   
..                         ...                     ...   
95                      Guyana     (188)169-1674x58692   
96                   Sri Lanka         +1-846-706-2218   
97             Solomon Islands    +1-753-067-8419x7170   
98                       Aruba           (530)311-9786   
99                    Honduras           (753)813-6941   

                   Phone 2                           Email Subscription Date  \
0         397.884.0519x718        zunigavanessa@smith.info        2020-08-24   
1         686-620-1820x944                 vmata@colon.com        2021-04-23   
2      (496)978-3969x58947             beckycarr@hogan.com        2020-03-25   
3          +1-813-324-8756     stanleyblackwell@benson.org        2020-06-02   
4    001-199-446-3860x3486         colinalvarado@miles.net        2021-04-17   
..                     ...                             ...               ...   
95    001-841-293-3519x614                hhart@jensen.com        2022-01-30   
96            605.413.3198               vkemp@ferrell.com        2021-07-10   
97   +1-632-666-7507x92121                swagner@kane.org        2021-09-18   
98  001-869-452-0943x12424  mccarthystephen@horn-green.biz        2021-08-11   
99            783.639.1472          colleen91@faulkner.biz        2020-03-11   

                              Website  
0          http://www.stephenson.com/  
1               http://www.hobbs.com/  
2            http://www.lawrence.com/  
3          http://www.good-lyons.com/  
4         https://goodwin-ingram.com/  
..                                ...  
95            http://hayes-perez.com/  
96         https://novak-allison.com/  
97              https://www.ross.com/  
98               http://watkins.info/  
99  http://www.hatfield-saunders.net/  

[100 rows x 12 columns]

In [5]:
a=pd.read_csv("C:/Users/raghu/Downloads/csv_file/customers-100.csv")
a

Index      Customer Id First Name Last Name  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter   
1       2  1Ef7b82A4CAAD10    Preston    Lozano   
2       3  6F94879bDAfE5a6        Roy     Berry   
3       4  5Cef8BFA16c5e3c      Linda     Olsen   
4       5  053d585Ab6b3159     Joanna    Bender   
..    ...              ...        ...       ...   
95     96  cb8E23e48d22Eae       Karl     Greer   
96     97  CeD220bdAaCfaDf       Lynn  Atkinson   
97     98  28CDbC0dFe4b1Db       Fred    Guerra   
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer   
99    100  2354a0E336A91A1   Clarence    Haynes   

                            Company               City  \
0                   Rasmussen Group       East Leonard   
1                       Vega-Gentry  East Jimmychester   
2                     Murillo-Perry      Isabelborough   
3   Dominguez, Mcmillan and Donovan         Bensonview   
4          Martin, Lang and Andrade     West Priscilla   
..                              ...                ...   
95                        Carey LLC       East Richard   
96            Ware, Burns and Oneal       New Bradview   
97                    Schmitt-Jones         Ortegaland   
98               Fitzgerald-Harrell    Lake Elijahview   
99               Le, Nash and Cross          Judymouth   

                       Country                 Phone 1  \
0                        Chile            229.077.5154   
1                     Djibouti              5153435776   
2          Antigua and Barbuda         +1-539-402-0259   
3           Dominican Republic  001-808-617-6467x12895   
4   Slovakia (Slovak Republic)  001-234-203-0635x76146   
..                         ...                     ...   
95                      Guyana     (188)169-1674x58692   
96                   Sri Lanka         +1-846-706-2218   
97             Solomon Islands    +1-753-067-8419x7170   
98                       Aruba           (530)311-9786   
99                    Honduras           (753)813-6941   

                   Phone 2                           Email Subscription Date  \
0         397.884.0519x718        zunigavanessa@smith.info        2020-08-24   
1         686-620-1820x944                 vmata@colon.com        2021-04-23   
2      (496)978-3969x58947             beckycarr@hogan.com        2020-03-25   
3          +1-813-324-8756     stanleyblackwell@benson.org        2020-06-02   
4    001-199-446-3860x3486         colinalvarado@miles.net        2021-04-17   
..                     ...                             ...               ...   
95    001-841-293-3519x614                hhart@jensen.com        2022-01-30   
96            605.413.3198               vkemp@ferrell.com        2021-07-10   
97   +1-632-666-7507x92121                swagner@kane.org        2021-09-18   
98  001-869-452-0943x12424  mccarthystephen@horn-green.biz        2021-08-11   
99            783.639.1472          colleen91@faulkner.biz        2020-03-11   

                              Website  
0          http://www.stephenson.com/  
1               http://www.hobbs.com/  
2            http://www.lawrence.com/  
3          http://www.good-lyons.com/  
4         https://goodwin-ingram.com/  
..                                ...  
95            http://hayes-perez.com/  
96         https://novak-allison.com/  
97              https://www.ross.com/  
98               http://watkins.info/  
99  http://www.hatfield-saunders.net/  

[100 rows x 12 columns]

In [8]:
a = pd.array([1,2,3,4])
a

<IntegerArray>
[1, 2, 3, 4]
Length: 4, dtype: Int64